sudo: required
language: php
php:
  - '7.1'
services: docker

cache:
  directories:
  - vendor

before_install:
  - docker-compose up -d
  - docker-compose ps
  - phpenv config-rm xdebug.ini

install:
  - composer install
  - cp .env.testing .env
  - php artisan key:generate
  - docker-compose exec app php artisan passport:install

script:
  - docker-compose exec app vendor/bin/phpunit
