sudo: required
language: php
services: docker

before_install:
  - pwd
  - ls -llh
  - docker-compose --version
  - docker-compose up -d
  - docker-compose ps

script:
  - docker run --rm -v $(pwd):/app composer/composer install
  - docker-compose exec app vendor/bin/phpunit
