sudo: required
language: php
services: docker

before_install:
  - pwd
  - ls -llh
  - docker-coompose --version
  - docker-compose up -d
  - docker-compose ps

script:
  - docker-compose exec app vendor/bin/phpunit
