sudo: required
language: php
services: docker

before_install:
  - docker-compose up -d
  - docker-compose ps
  - composer install
  - cp .env.testing .env
  - docker-compose exec app php artisan key:generate

script:
  - docker-compose exec app vendor/bin/phpunit
